version: "3"

services:
  mailverifier:
    image: ghcr.io/hhn-mc/mailverifier:latest
    container_name: mailverifier
    restart: unless-stopped
    volumes:
      - ./data/mailverifier:/configs
    networks:
      - mailverifier
      - hhnmc
    depends_on:
      - postgres
    environment:
      MAILVERIFIER_CONFIG_PATH: "/configs/config.yml"

  postgres:
    image: postgres:latest
    container_name: mailverifier-postgres
    networks:
      - mailverifier
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

networks:
  mailverifier:
    name: mailverifier
  hhnmc:
    external: true