version: "3"

services:
  mailverifier:
    build:
      context: ..
      dockerfile: build/Dockerfile
    container_name: mailverifier
    restart: unless-stopped
    volumes:
      - ./:/configs
    networks:
      - mailverifier
      - traefik
    labels:
      - traefik.enable=true
      - traefik.http.routers.mailverifier.rule=Host(`mailverifier.dev.hhn-mc.de`)
      - traefik.http.routers.mailverifier.entrypoints=websecure
      - traefik.http.routers.mailverifier.tls=true
      - traefik.http.routers.mailverifier.tls.certresolver=lets-encrypt
      - traefik.http.services.mailverifier.loadbalancer.server.port=8080
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    container_name: mailverifier-postgres
    restart: unless-stopped
    networks:
      - mailverifier
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres

networks:
  mailverifier:
    name: mailverifier
  traefik:
    external: true