version: "3"

services:
  mailverifier:
    build:
      context: ..
      dockerfile: build/package/Dockerfile
    container_name: mailverifier
    restart: unless-stopped
    volumes:
      - ../configs/config.dev.yml:/config.yml
    depends_on:
      - postgres
    ports:
      - 8080:8080

  postgres:
    image: postgres:latest
    container_name: mailverifier-postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
