version: "3"

services:
  mailverifier:
    build: .
    container_name: mailverifier
    restart: unless-stopped
    volumes:
      - ./config.yml:/configs/config.dev.yaml
    networks:
      - mailverifier
      - traefik
    labels:
      - traefik.enable=true
      - traefik.http.routers.mailverifier.rule=Host(`mailverifier.dev.hhn-mc.de`)
      - traefik.http.routers.mailverifier.entrypoints=websecure
      - traefik.http.routers.mailverifier.tls=true
      - traefik.http.routers.mailverifier.tls.certresolver=lets-encrypt
      - traefik.http.services.mailverifier.loadbalancer.server.port=8080

  postgres:
        image: postgres:latest
        container_name: postgres
        networks:
          - mailverifier
        environment:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
        volumes:
          - ./postgres:/var/lib/postgresql/data

networks:
  mailverifier:
    name: mailverifier
  traefik:
    external: true